package com.sme.be_sme.modules.onboarding.infrastructure.persistence.entity;

import java.util.Date;

public class ChecklistTemplateEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checklist_templates.checklist_template_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String checklistTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checklist_templates.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checklist_templates.onboarding_template_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String onboardingTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checklist_templates.name
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checklist_templates.stage
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String stage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checklist_templates.sort_order
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checklist_templates.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checklist_templates.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checklist_templates.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checklist_templates.checklist_template_id
     *
     * @return the value of checklist_templates.checklist_template_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getChecklistTemplateId() {
        return checklistTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checklist_templates.checklist_template_id
     *
     * @param checklistTemplateId the value for checklist_templates.checklist_template_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setChecklistTemplateId(String checklistTemplateId) {
        this.checklistTemplateId = checklistTemplateId == null ? null : checklistTemplateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checklist_templates.company_id
     *
     * @return the value of checklist_templates.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checklist_templates.company_id
     *
     * @param companyId the value for checklist_templates.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checklist_templates.onboarding_template_id
     *
     * @return the value of checklist_templates.onboarding_template_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getOnboardingTemplateId() {
        return onboardingTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checklist_templates.onboarding_template_id
     *
     * @param onboardingTemplateId the value for checklist_templates.onboarding_template_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setOnboardingTemplateId(String onboardingTemplateId) {
        this.onboardingTemplateId = onboardingTemplateId == null ? null : onboardingTemplateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checklist_templates.name
     *
     * @return the value of checklist_templates.name
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checklist_templates.name
     *
     * @param name the value for checklist_templates.name
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checklist_templates.stage
     *
     * @return the value of checklist_templates.stage
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getStage() {
        return stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checklist_templates.stage
     *
     * @param stage the value for checklist_templates.stage
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setStage(String stage) {
        this.stage = stage == null ? null : stage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checklist_templates.sort_order
     *
     * @return the value of checklist_templates.sort_order
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checklist_templates.sort_order
     *
     * @param sortOrder the value for checklist_templates.sort_order
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checklist_templates.status
     *
     * @return the value of checklist_templates.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checklist_templates.status
     *
     * @param status the value for checklist_templates.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checklist_templates.created_at
     *
     * @return the value of checklist_templates.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checklist_templates.created_at
     *
     * @param createdAt the value for checklist_templates.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checklist_templates.updated_at
     *
     * @return the value of checklist_templates.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checklist_templates.updated_at
     *
     * @param updatedAt the value for checklist_templates.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}