package com.sme.be_sme.modules.onboarding.infrastructure.persistence.entity;

import java.util.Date;

public class OnboardingEventEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_events.onboarding_event_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String onboardingEventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_events.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_events.onboarding_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String onboardingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_events.actor_user_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String actorUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_events.event_type
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String eventType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_events.event_data
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Object eventData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_events.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_events.onboarding_event_id
     *
     * @return the value of onboarding_events.onboarding_event_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getOnboardingEventId() {
        return onboardingEventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_events.onboarding_event_id
     *
     * @param onboardingEventId the value for onboarding_events.onboarding_event_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setOnboardingEventId(String onboardingEventId) {
        this.onboardingEventId = onboardingEventId == null ? null : onboardingEventId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_events.company_id
     *
     * @return the value of onboarding_events.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_events.company_id
     *
     * @param companyId the value for onboarding_events.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_events.onboarding_id
     *
     * @return the value of onboarding_events.onboarding_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getOnboardingId() {
        return onboardingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_events.onboarding_id
     *
     * @param onboardingId the value for onboarding_events.onboarding_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setOnboardingId(String onboardingId) {
        this.onboardingId = onboardingId == null ? null : onboardingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_events.actor_user_id
     *
     * @return the value of onboarding_events.actor_user_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getActorUserId() {
        return actorUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_events.actor_user_id
     *
     * @param actorUserId the value for onboarding_events.actor_user_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setActorUserId(String actorUserId) {
        this.actorUserId = actorUserId == null ? null : actorUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_events.event_type
     *
     * @return the value of onboarding_events.event_type
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_events.event_type
     *
     * @param eventType the value for onboarding_events.event_type
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setEventType(String eventType) {
        this.eventType = eventType == null ? null : eventType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_events.event_data
     *
     * @return the value of onboarding_events.event_data
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Object getEventData() {
        return eventData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_events.event_data
     *
     * @param eventData the value for onboarding_events.event_data
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setEventData(Object eventData) {
        this.eventData = eventData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_events.created_at
     *
     * @return the value of onboarding_events.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_events.created_at
     *
     * @param createdAt the value for onboarding_events.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}