package com.sme.be_sme.modules.onboarding.infrastructure.persistence.entity;

import java.util.Date;

public class OnboardingTemplateEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_templates.onboarding_template_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String onboardingTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_templates.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_templates.name
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_templates.description
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_templates.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_templates.created_by
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_templates.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_templates.updated_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_templates.onboarding_template_id
     *
     * @return the value of onboarding_templates.onboarding_template_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getOnboardingTemplateId() {
        return onboardingTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_templates.onboarding_template_id
     *
     * @param onboardingTemplateId the value for onboarding_templates.onboarding_template_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setOnboardingTemplateId(String onboardingTemplateId) {
        this.onboardingTemplateId = onboardingTemplateId == null ? null : onboardingTemplateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_templates.company_id
     *
     * @return the value of onboarding_templates.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_templates.company_id
     *
     * @param companyId the value for onboarding_templates.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_templates.name
     *
     * @return the value of onboarding_templates.name
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_templates.name
     *
     * @param name the value for onboarding_templates.name
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_templates.description
     *
     * @return the value of onboarding_templates.description
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_templates.description
     *
     * @param description the value for onboarding_templates.description
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_templates.status
     *
     * @return the value of onboarding_templates.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_templates.status
     *
     * @param status the value for onboarding_templates.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_templates.created_by
     *
     * @return the value of onboarding_templates.created_by
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_templates.created_by
     *
     * @param createdBy the value for onboarding_templates.created_by
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_templates.created_at
     *
     * @return the value of onboarding_templates.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_templates.created_at
     *
     * @param createdAt the value for onboarding_templates.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_templates.updated_at
     *
     * @return the value of onboarding_templates.updated_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_templates.updated_at
     *
     * @param updatedAt the value for onboarding_templates.updated_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}