package com.sme.be_sme.modules.onboarding.infrastructure.persistence.entity;

import java.util.Date;

public class OnboardingInstanceEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_instances.onboarding_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String onboardingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_instances.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_instances.employee_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_instances.onboarding_template_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String onboardingTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_instances.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_instances.start_date
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_instances.completed_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date completedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_instances.created_by
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_instances.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onboarding_instances.updated_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_instances.onboarding_id
     *
     * @return the value of onboarding_instances.onboarding_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getOnboardingId() {
        return onboardingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_instances.onboarding_id
     *
     * @param onboardingId the value for onboarding_instances.onboarding_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setOnboardingId(String onboardingId) {
        this.onboardingId = onboardingId == null ? null : onboardingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_instances.company_id
     *
     * @return the value of onboarding_instances.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_instances.company_id
     *
     * @param companyId the value for onboarding_instances.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_instances.employee_id
     *
     * @return the value of onboarding_instances.employee_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_instances.employee_id
     *
     * @param employeeId the value for onboarding_instances.employee_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_instances.onboarding_template_id
     *
     * @return the value of onboarding_instances.onboarding_template_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getOnboardingTemplateId() {
        return onboardingTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_instances.onboarding_template_id
     *
     * @param onboardingTemplateId the value for onboarding_instances.onboarding_template_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setOnboardingTemplateId(String onboardingTemplateId) {
        this.onboardingTemplateId = onboardingTemplateId == null ? null : onboardingTemplateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_instances.status
     *
     * @return the value of onboarding_instances.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_instances.status
     *
     * @param status the value for onboarding_instances.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_instances.start_date
     *
     * @return the value of onboarding_instances.start_date
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_instances.start_date
     *
     * @param startDate the value for onboarding_instances.start_date
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_instances.completed_at
     *
     * @return the value of onboarding_instances.completed_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getCompletedAt() {
        return completedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_instances.completed_at
     *
     * @param completedAt the value for onboarding_instances.completed_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCompletedAt(Date completedAt) {
        this.completedAt = completedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_instances.created_by
     *
     * @return the value of onboarding_instances.created_by
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_instances.created_by
     *
     * @param createdBy the value for onboarding_instances.created_by
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_instances.created_at
     *
     * @return the value of onboarding_instances.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_instances.created_at
     *
     * @param createdAt the value for onboarding_instances.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onboarding_instances.updated_at
     *
     * @return the value of onboarding_instances.updated_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onboarding_instances.updated_at
     *
     * @param updatedAt the value for onboarding_instances.updated_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}