package com.sme.be_sme.modules.onboarding.infrastructure.persistence.entity;

import java.util.Date;

public class TaskActivityLogEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_activity_logs.task_activity_log_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String taskActivityLogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_activity_logs.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_activity_logs.task_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_activity_logs.actor_user_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String actorUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_activity_logs.action
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_activity_logs.old_value
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String oldValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_activity_logs.new_value
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String newValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_activity_logs.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_activity_logs.task_activity_log_id
     *
     * @return the value of task_activity_logs.task_activity_log_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getTaskActivityLogId() {
        return taskActivityLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_activity_logs.task_activity_log_id
     *
     * @param taskActivityLogId the value for task_activity_logs.task_activity_log_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setTaskActivityLogId(String taskActivityLogId) {
        this.taskActivityLogId = taskActivityLogId == null ? null : taskActivityLogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_activity_logs.company_id
     *
     * @return the value of task_activity_logs.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_activity_logs.company_id
     *
     * @param companyId the value for task_activity_logs.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_activity_logs.task_id
     *
     * @return the value of task_activity_logs.task_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_activity_logs.task_id
     *
     * @param taskId the value for task_activity_logs.task_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_activity_logs.actor_user_id
     *
     * @return the value of task_activity_logs.actor_user_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getActorUserId() {
        return actorUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_activity_logs.actor_user_id
     *
     * @param actorUserId the value for task_activity_logs.actor_user_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setActorUserId(String actorUserId) {
        this.actorUserId = actorUserId == null ? null : actorUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_activity_logs.action
     *
     * @return the value of task_activity_logs.action
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_activity_logs.action
     *
     * @param action the value for task_activity_logs.action
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_activity_logs.old_value
     *
     * @return the value of task_activity_logs.old_value
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getOldValue() {
        return oldValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_activity_logs.old_value
     *
     * @param oldValue the value for task_activity_logs.old_value
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setOldValue(String oldValue) {
        this.oldValue = oldValue == null ? null : oldValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_activity_logs.new_value
     *
     * @return the value of task_activity_logs.new_value
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getNewValue() {
        return newValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_activity_logs.new_value
     *
     * @param newValue the value for task_activity_logs.new_value
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setNewValue(String newValue) {
        this.newValue = newValue == null ? null : newValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_activity_logs.created_at
     *
     * @return the value of task_activity_logs.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_activity_logs.created_at
     *
     * @param createdAt the value for task_activity_logs.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}