package com.sme.be_sme.modules.onboarding.infrastructure.persistence.entity;

import java.util.Date;

public class TaskInstanceEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_instances.task_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_instances.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_instances.checklist_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String checklistId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_instances.task_template_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String taskTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_instances.title
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_instances.description
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_instances.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_instances.due_date
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date dueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_instances.assigned_user_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String assignedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_instances.assigned_department_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String assignedDepartmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_instances.completed_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date completedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_instances.created_by
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_instances.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_instances.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_instances.task_id
     *
     * @return the value of task_instances.task_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_instances.task_id
     *
     * @param taskId the value for task_instances.task_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_instances.company_id
     *
     * @return the value of task_instances.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_instances.company_id
     *
     * @param companyId the value for task_instances.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_instances.checklist_id
     *
     * @return the value of task_instances.checklist_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getChecklistId() {
        return checklistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_instances.checklist_id
     *
     * @param checklistId the value for task_instances.checklist_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setChecklistId(String checklistId) {
        this.checklistId = checklistId == null ? null : checklistId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_instances.task_template_id
     *
     * @return the value of task_instances.task_template_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getTaskTemplateId() {
        return taskTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_instances.task_template_id
     *
     * @param taskTemplateId the value for task_instances.task_template_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setTaskTemplateId(String taskTemplateId) {
        this.taskTemplateId = taskTemplateId == null ? null : taskTemplateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_instances.title
     *
     * @return the value of task_instances.title
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_instances.title
     *
     * @param title the value for task_instances.title
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_instances.description
     *
     * @return the value of task_instances.description
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_instances.description
     *
     * @param description the value for task_instances.description
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_instances.status
     *
     * @return the value of task_instances.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_instances.status
     *
     * @param status the value for task_instances.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_instances.due_date
     *
     * @return the value of task_instances.due_date
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_instances.due_date
     *
     * @param dueDate the value for task_instances.due_date
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_instances.assigned_user_id
     *
     * @return the value of task_instances.assigned_user_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getAssignedUserId() {
        return assignedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_instances.assigned_user_id
     *
     * @param assignedUserId the value for task_instances.assigned_user_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setAssignedUserId(String assignedUserId) {
        this.assignedUserId = assignedUserId == null ? null : assignedUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_instances.assigned_department_id
     *
     * @return the value of task_instances.assigned_department_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getAssignedDepartmentId() {
        return assignedDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_instances.assigned_department_id
     *
     * @param assignedDepartmentId the value for task_instances.assigned_department_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setAssignedDepartmentId(String assignedDepartmentId) {
        this.assignedDepartmentId = assignedDepartmentId == null ? null : assignedDepartmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_instances.completed_at
     *
     * @return the value of task_instances.completed_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCompletedAt() {
        return completedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_instances.completed_at
     *
     * @param completedAt the value for task_instances.completed_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompletedAt(Date completedAt) {
        this.completedAt = completedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_instances.created_by
     *
     * @return the value of task_instances.created_by
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_instances.created_by
     *
     * @param createdBy the value for task_instances.created_by
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_instances.created_at
     *
     * @return the value of task_instances.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_instances.created_at
     *
     * @param createdAt the value for task_instances.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_instances.updated_at
     *
     * @return the value of task_instances.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_instances.updated_at
     *
     * @param updatedAt the value for task_instances.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}