package com.sme.be_sme.modules.onboarding.infrastructure.persistence.entity;

import java.util.Date;

public class TaskCommentEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_comments.task_comment_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String taskCommentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_comments.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_comments.task_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_comments.content
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_comments.created_by
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_comments.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_comments.task_comment_id
     *
     * @return the value of task_comments.task_comment_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getTaskCommentId() {
        return taskCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_comments.task_comment_id
     *
     * @param taskCommentId the value for task_comments.task_comment_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setTaskCommentId(String taskCommentId) {
        this.taskCommentId = taskCommentId == null ? null : taskCommentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_comments.company_id
     *
     * @return the value of task_comments.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_comments.company_id
     *
     * @param companyId the value for task_comments.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_comments.task_id
     *
     * @return the value of task_comments.task_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_comments.task_id
     *
     * @param taskId the value for task_comments.task_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_comments.content
     *
     * @return the value of task_comments.content
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_comments.content
     *
     * @param content the value for task_comments.content
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_comments.created_by
     *
     * @return the value of task_comments.created_by
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_comments.created_by
     *
     * @param createdBy the value for task_comments.created_by
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_comments.created_at
     *
     * @return the value of task_comments.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_comments.created_at
     *
     * @param createdAt the value for task_comments.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}