package com.sme.be_sme.modules.onboarding.infrastructure.persistence.entity;

import java.util.Date;

public class TaskTemplateEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_templates.task_template_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String taskTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_templates.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_templates.checklist_template_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String checklistTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_templates.title
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_templates.description
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_templates.owner_type
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String ownerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_templates.owner_ref_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String ownerRefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_templates.due_days_offset
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Integer dueDaysOffset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_templates.require_ack
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Boolean requireAck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_templates.sort_order
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_templates.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_templates.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_templates.updated_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_templates.task_template_id
     *
     * @return the value of task_templates.task_template_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getTaskTemplateId() {
        return taskTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_templates.task_template_id
     *
     * @param taskTemplateId the value for task_templates.task_template_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setTaskTemplateId(String taskTemplateId) {
        this.taskTemplateId = taskTemplateId == null ? null : taskTemplateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_templates.company_id
     *
     * @return the value of task_templates.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_templates.company_id
     *
     * @param companyId the value for task_templates.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_templates.checklist_template_id
     *
     * @return the value of task_templates.checklist_template_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getChecklistTemplateId() {
        return checklistTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_templates.checklist_template_id
     *
     * @param checklistTemplateId the value for task_templates.checklist_template_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setChecklistTemplateId(String checklistTemplateId) {
        this.checklistTemplateId = checklistTemplateId == null ? null : checklistTemplateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_templates.title
     *
     * @return the value of task_templates.title
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_templates.title
     *
     * @param title the value for task_templates.title
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_templates.description
     *
     * @return the value of task_templates.description
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_templates.description
     *
     * @param description the value for task_templates.description
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_templates.owner_type
     *
     * @return the value of task_templates.owner_type
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getOwnerType() {
        return ownerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_templates.owner_type
     *
     * @param ownerType the value for task_templates.owner_type
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setOwnerType(String ownerType) {
        this.ownerType = ownerType == null ? null : ownerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_templates.owner_ref_id
     *
     * @return the value of task_templates.owner_ref_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getOwnerRefId() {
        return ownerRefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_templates.owner_ref_id
     *
     * @param ownerRefId the value for task_templates.owner_ref_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setOwnerRefId(String ownerRefId) {
        this.ownerRefId = ownerRefId == null ? null : ownerRefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_templates.due_days_offset
     *
     * @return the value of task_templates.due_days_offset
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Integer getDueDaysOffset() {
        return dueDaysOffset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_templates.due_days_offset
     *
     * @param dueDaysOffset the value for task_templates.due_days_offset
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setDueDaysOffset(Integer dueDaysOffset) {
        this.dueDaysOffset = dueDaysOffset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_templates.require_ack
     *
     * @return the value of task_templates.require_ack
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Boolean getRequireAck() {
        return requireAck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_templates.require_ack
     *
     * @param requireAck the value for task_templates.require_ack
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setRequireAck(Boolean requireAck) {
        this.requireAck = requireAck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_templates.sort_order
     *
     * @return the value of task_templates.sort_order
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_templates.sort_order
     *
     * @param sortOrder the value for task_templates.sort_order
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_templates.status
     *
     * @return the value of task_templates.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_templates.status
     *
     * @param status the value for task_templates.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_templates.created_at
     *
     * @return the value of task_templates.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_templates.created_at
     *
     * @param createdAt the value for task_templates.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_templates.updated_at
     *
     * @return the value of task_templates.updated_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_templates.updated_at
     *
     * @param updatedAt the value for task_templates.updated_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}