package com.sme.be_sme.modules.notification.infrastructure.persistence.entity;

import java.util.Date;

public class NotificationEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.notification_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String notificationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.user_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.type
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.title
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.content
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.ref_type
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String refType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.ref_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String refId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.read_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date readAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.notification_id
     *
     * @return the value of notifications.notification_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getNotificationId() {
        return notificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.notification_id
     *
     * @param notificationId the value for notifications.notification_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setNotificationId(String notificationId) {
        this.notificationId = notificationId == null ? null : notificationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.company_id
     *
     * @return the value of notifications.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.company_id
     *
     * @param companyId the value for notifications.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.user_id
     *
     * @return the value of notifications.user_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.user_id
     *
     * @param userId the value for notifications.user_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.type
     *
     * @return the value of notifications.type
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.type
     *
     * @param type the value for notifications.type
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.title
     *
     * @return the value of notifications.title
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.title
     *
     * @param title the value for notifications.title
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.content
     *
     * @return the value of notifications.content
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.content
     *
     * @param content the value for notifications.content
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.status
     *
     * @return the value of notifications.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.status
     *
     * @param status the value for notifications.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.ref_type
     *
     * @return the value of notifications.ref_type
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getRefType() {
        return refType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.ref_type
     *
     * @param refType the value for notifications.ref_type
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setRefType(String refType) {
        this.refType = refType == null ? null : refType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.ref_id
     *
     * @return the value of notifications.ref_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.ref_id
     *
     * @param refId the value for notifications.ref_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setRefId(String refId) {
        this.refId = refId == null ? null : refId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.created_at
     *
     * @return the value of notifications.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.created_at
     *
     * @param createdAt the value for notifications.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.read_at
     *
     * @return the value of notifications.read_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getReadAt() {
        return readAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.read_at
     *
     * @param readAt the value for notifications.read_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setReadAt(Date readAt) {
        this.readAt = readAt;
    }
}