package com.sme.be_sme.modules.automation.infrastructure.persistence.entity;

import java.util.Date;

public class AutomationRuleEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column automation_rules.automation_rule_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String automationRuleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column automation_rules.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column automation_rules.name
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column automation_rules.rule_type
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String ruleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column automation_rules.email_campaign_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String emailCampaignId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column automation_rules.action_type
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String actionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column automation_rules.condition_json
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Object conditionJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column automation_rules.schedule_json
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Object scheduleJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column automation_rules.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column automation_rules.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column automation_rules.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column automation_rules.automation_rule_id
     *
     * @return the value of automation_rules.automation_rule_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getAutomationRuleId() {
        return automationRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column automation_rules.automation_rule_id
     *
     * @param automationRuleId the value for automation_rules.automation_rule_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setAutomationRuleId(String automationRuleId) {
        this.automationRuleId = automationRuleId == null ? null : automationRuleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column automation_rules.company_id
     *
     * @return the value of automation_rules.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column automation_rules.company_id
     *
     * @param companyId the value for automation_rules.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column automation_rules.name
     *
     * @return the value of automation_rules.name
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column automation_rules.name
     *
     * @param name the value for automation_rules.name
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column automation_rules.rule_type
     *
     * @return the value of automation_rules.rule_type
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getRuleType() {
        return ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column automation_rules.rule_type
     *
     * @param ruleType the value for automation_rules.rule_type
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setRuleType(String ruleType) {
        this.ruleType = ruleType == null ? null : ruleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column automation_rules.email_campaign_id
     *
     * @return the value of automation_rules.email_campaign_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getEmailCampaignId() {
        return emailCampaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column automation_rules.email_campaign_id
     *
     * @param emailCampaignId the value for automation_rules.email_campaign_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setEmailCampaignId(String emailCampaignId) {
        this.emailCampaignId = emailCampaignId == null ? null : emailCampaignId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column automation_rules.action_type
     *
     * @return the value of automation_rules.action_type
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getActionType() {
        return actionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column automation_rules.action_type
     *
     * @param actionType the value for automation_rules.action_type
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setActionType(String actionType) {
        this.actionType = actionType == null ? null : actionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column automation_rules.condition_json
     *
     * @return the value of automation_rules.condition_json
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Object getConditionJson() {
        return conditionJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column automation_rules.condition_json
     *
     * @param conditionJson the value for automation_rules.condition_json
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setConditionJson(Object conditionJson) {
        this.conditionJson = conditionJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column automation_rules.schedule_json
     *
     * @return the value of automation_rules.schedule_json
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Object getScheduleJson() {
        return scheduleJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column automation_rules.schedule_json
     *
     * @param scheduleJson the value for automation_rules.schedule_json
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setScheduleJson(Object scheduleJson) {
        this.scheduleJson = scheduleJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column automation_rules.status
     *
     * @return the value of automation_rules.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column automation_rules.status
     *
     * @param status the value for automation_rules.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column automation_rules.created_at
     *
     * @return the value of automation_rules.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column automation_rules.created_at
     *
     * @param createdAt the value for automation_rules.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column automation_rules.updated_at
     *
     * @return the value of automation_rules.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column automation_rules.updated_at
     *
     * @param updatedAt the value for automation_rules.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}