package com.sme.be_sme.modules.automation.infrastructure.persistence.entity;

import java.util.Date;

public class EmailCampaignEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_campaigns.email_campaign_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String emailCampaignId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_campaigns.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_campaigns.email_template_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String emailTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_campaigns.name
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_campaigns.trigger_type
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String triggerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_campaigns.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_campaigns.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_campaigns.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_campaigns.email_campaign_id
     *
     * @return the value of email_campaigns.email_campaign_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getEmailCampaignId() {
        return emailCampaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_campaigns.email_campaign_id
     *
     * @param emailCampaignId the value for email_campaigns.email_campaign_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setEmailCampaignId(String emailCampaignId) {
        this.emailCampaignId = emailCampaignId == null ? null : emailCampaignId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_campaigns.company_id
     *
     * @return the value of email_campaigns.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_campaigns.company_id
     *
     * @param companyId the value for email_campaigns.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_campaigns.email_template_id
     *
     * @return the value of email_campaigns.email_template_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getEmailTemplateId() {
        return emailTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_campaigns.email_template_id
     *
     * @param emailTemplateId the value for email_campaigns.email_template_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setEmailTemplateId(String emailTemplateId) {
        this.emailTemplateId = emailTemplateId == null ? null : emailTemplateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_campaigns.name
     *
     * @return the value of email_campaigns.name
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_campaigns.name
     *
     * @param name the value for email_campaigns.name
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_campaigns.trigger_type
     *
     * @return the value of email_campaigns.trigger_type
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getTriggerType() {
        return triggerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_campaigns.trigger_type
     *
     * @param triggerType the value for email_campaigns.trigger_type
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setTriggerType(String triggerType) {
        this.triggerType = triggerType == null ? null : triggerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_campaigns.status
     *
     * @return the value of email_campaigns.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_campaigns.status
     *
     * @param status the value for email_campaigns.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_campaigns.created_at
     *
     * @return the value of email_campaigns.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_campaigns.created_at
     *
     * @param createdAt the value for email_campaigns.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_campaigns.updated_at
     *
     * @return the value of email_campaigns.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_campaigns.updated_at
     *
     * @param updatedAt the value for email_campaigns.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}