package com.sme.be_sme.modules.automation.infrastructure.persistence.entity;

import java.util.Date;

public class EmailLogEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_logs.email_log_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String emailLogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_logs.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_logs.email_campaign_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String emailCampaignId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_logs.onboarding_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String onboardingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_logs.user_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_logs.to_email
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String toEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_logs.subject
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_logs.provider
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String provider;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_logs.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_logs.error_message
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String errorMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_logs.queued_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date queuedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_logs.sent_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date sentAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_logs.email_log_id
     *
     * @return the value of email_logs.email_log_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getEmailLogId() {
        return emailLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_logs.email_log_id
     *
     * @param emailLogId the value for email_logs.email_log_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setEmailLogId(String emailLogId) {
        this.emailLogId = emailLogId == null ? null : emailLogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_logs.company_id
     *
     * @return the value of email_logs.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_logs.company_id
     *
     * @param companyId the value for email_logs.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_logs.email_campaign_id
     *
     * @return the value of email_logs.email_campaign_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getEmailCampaignId() {
        return emailCampaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_logs.email_campaign_id
     *
     * @param emailCampaignId the value for email_logs.email_campaign_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setEmailCampaignId(String emailCampaignId) {
        this.emailCampaignId = emailCampaignId == null ? null : emailCampaignId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_logs.onboarding_id
     *
     * @return the value of email_logs.onboarding_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getOnboardingId() {
        return onboardingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_logs.onboarding_id
     *
     * @param onboardingId the value for email_logs.onboarding_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setOnboardingId(String onboardingId) {
        this.onboardingId = onboardingId == null ? null : onboardingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_logs.user_id
     *
     * @return the value of email_logs.user_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_logs.user_id
     *
     * @param userId the value for email_logs.user_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_logs.to_email
     *
     * @return the value of email_logs.to_email
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getToEmail() {
        return toEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_logs.to_email
     *
     * @param toEmail the value for email_logs.to_email
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setToEmail(String toEmail) {
        this.toEmail = toEmail == null ? null : toEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_logs.subject
     *
     * @return the value of email_logs.subject
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_logs.subject
     *
     * @param subject the value for email_logs.subject
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_logs.provider
     *
     * @return the value of email_logs.provider
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getProvider() {
        return provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_logs.provider
     *
     * @param provider the value for email_logs.provider
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setProvider(String provider) {
        this.provider = provider == null ? null : provider.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_logs.status
     *
     * @return the value of email_logs.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_logs.status
     *
     * @param status the value for email_logs.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_logs.error_message
     *
     * @return the value of email_logs.error_message
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_logs.error_message
     *
     * @param errorMessage the value for email_logs.error_message
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage == null ? null : errorMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_logs.queued_at
     *
     * @return the value of email_logs.queued_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getQueuedAt() {
        return queuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_logs.queued_at
     *
     * @param queuedAt the value for email_logs.queued_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setQueuedAt(Date queuedAt) {
        this.queuedAt = queuedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_logs.sent_at
     *
     * @return the value of email_logs.sent_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getSentAt() {
        return sentAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_logs.sent_at
     *
     * @param sentAt the value for email_logs.sent_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setSentAt(Date sentAt) {
        this.sentAt = sentAt;
    }
}