package com.sme.be_sme.modules.automation.infrastructure.persistence.entity;

import java.util.Date;

public class EmailTemplateEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_templates.email_template_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String emailTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_templates.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_templates.name
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_templates.subject_template
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String subjectTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_templates.body_template
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String bodyTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_templates.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_templates.created_by
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_templates.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email_templates.updated_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_templates.email_template_id
     *
     * @return the value of email_templates.email_template_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getEmailTemplateId() {
        return emailTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_templates.email_template_id
     *
     * @param emailTemplateId the value for email_templates.email_template_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setEmailTemplateId(String emailTemplateId) {
        this.emailTemplateId = emailTemplateId == null ? null : emailTemplateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_templates.company_id
     *
     * @return the value of email_templates.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_templates.company_id
     *
     * @param companyId the value for email_templates.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_templates.name
     *
     * @return the value of email_templates.name
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_templates.name
     *
     * @param name the value for email_templates.name
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_templates.subject_template
     *
     * @return the value of email_templates.subject_template
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getSubjectTemplate() {
        return subjectTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_templates.subject_template
     *
     * @param subjectTemplate the value for email_templates.subject_template
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setSubjectTemplate(String subjectTemplate) {
        this.subjectTemplate = subjectTemplate == null ? null : subjectTemplate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_templates.body_template
     *
     * @return the value of email_templates.body_template
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getBodyTemplate() {
        return bodyTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_templates.body_template
     *
     * @param bodyTemplate the value for email_templates.body_template
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setBodyTemplate(String bodyTemplate) {
        this.bodyTemplate = bodyTemplate == null ? null : bodyTemplate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_templates.status
     *
     * @return the value of email_templates.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_templates.status
     *
     * @param status the value for email_templates.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_templates.created_by
     *
     * @return the value of email_templates.created_by
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_templates.created_by
     *
     * @param createdBy the value for email_templates.created_by
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_templates.created_at
     *
     * @return the value of email_templates.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_templates.created_at
     *
     * @param createdAt the value for email_templates.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email_templates.updated_at
     *
     * @return the value of email_templates.updated_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email_templates.updated_at
     *
     * @param updatedAt the value for email_templates.updated_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}