package com.sme.be_sme.modules.company.infrastructure.mapper;

import com.sme.be_sme.modules.company.infrastructure.persistence.entity.CompanyEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface CompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companies
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companies
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(CompanyEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companies
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    CompanyEntity selectByPrimaryKey(String companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companies
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<CompanyEntity> selectAll();

    int countByTaxCodeOrName(@Param("taxCode") String taxCode,
                             @Param("name") String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companies
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(CompanyEntity row);
}
