package com.sme.be_sme.modules.company.infrastructure.mapper;

import com.sme.be_sme.modules.company.infrastructure.persistence.entity.CompanyEntity;
import java.util.List;

public interface CompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companies
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int deleteByPrimaryKey(String companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companies
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int insert(CompanyEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companies
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    CompanyEntity selectByPrimaryKey(String companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companies
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    List<CompanyEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table companies
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int updateByPrimaryKey(CompanyEntity row);
}