package com.sme.be_sme.modules.company.infrastructure.mapper;

import com.sme.be_sme.modules.company.infrastructure.persistence.entity.DepartmentEntity;
import java.util.List;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(DepartmentEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    DepartmentEntity selectByPrimaryKey(String departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<DepartmentEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(DepartmentEntity row);
}