package com.sme.be_sme.modules.company.infrastructure.mapper;

import com.sme.be_sme.modules.company.infrastructure.persistence.entity.DepartmentEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(DepartmentEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    DepartmentEntity selectByPrimaryKey(String departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<DepartmentEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(DepartmentEntity row);

    int countByCompanyAndName(@Param("companyId") String companyId,
                              @Param("name") String name);
}