version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: be_sme_postgres
    environment:
      POSTGRES_DB: be_sme
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog
    container_name: be_sme_mailhog
    ports:
      - "3025:1025"
      - "8025:8025"
