package com.sme.be_sme.modules.knowledge.infrastructure.mapper;

import com.sme.be_sme.modules.knowledge.infrastructure.persistence.entity.ChatMessageEntity;
import java.util.List;

public interface ChatMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_messages
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int deleteByPrimaryKey(String chatMessageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_messages
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int insert(ChatMessageEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_messages
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    ChatMessageEntity selectByPrimaryKey(String chatMessageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_messages
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    List<ChatMessageEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_messages
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int updateByPrimaryKey(ChatMessageEntity row);
}