package com.sme.be_sme.modules.knowledge.infrastructure.mapper;

import com.sme.be_sme.modules.knowledge.infrastructure.persistence.entity.ChatSessionEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ChatSessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_sessions
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String chatSessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_sessions
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(ChatSessionEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_sessions
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    ChatSessionEntity selectByPrimaryKey(String chatSessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_sessions
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<ChatSessionEntity> selectAll();

    /**
     * Select sessions by company and user, ordered by started_at desc.
     */
    List<ChatSessionEntity> selectByCompanyIdAndUserId(@Param("companyId") String companyId, @Param("userId") String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_sessions
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(ChatSessionEntity row);
}