package com.sme.be_sme.modules.knowledge.infrastructure.mapper;

import com.sme.be_sme.modules.knowledge.infrastructure.persistence.entity.ChatMessageEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ChatMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_messages
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String chatMessageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_messages
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(ChatMessageEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_messages
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    ChatMessageEntity selectByPrimaryKey(String chatMessageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_messages
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<ChatMessageEntity> selectAll();

    /**
     * Select messages by session, ordered by created_at asc.
     */
    List<ChatMessageEntity> selectBySessionIdOrderByCreatedAt(String chatSessionId);

    /**
     * Select first message (oldest) per session for given session IDs.
     * Uses DISTINCT ON in PostgreSQL.
     */
    List<ChatMessageEntity> selectFirstMessageBySessionIds(@Param("sessionIds") List<String> sessionIds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_messages
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(ChatMessageEntity row);
}