package com.sme.be_sme.modules.knowledge.infrastructure.mapper;

import com.sme.be_sme.modules.knowledge.infrastructure.persistence.entity.KbArticleTagEntity;
import java.util.List;

public interface KbArticleTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kb_article_tags
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String kbArticleTagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kb_article_tags
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(KbArticleTagEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kb_article_tags
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    KbArticleTagEntity selectByPrimaryKey(String kbArticleTagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kb_article_tags
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<KbArticleTagEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kb_article_tags
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(KbArticleTagEntity row);
}