package com.sme.be_sme.modules.knowledge.infrastructure.mapper;

import com.sme.be_sme.modules.knowledge.infrastructure.persistence.entity.KbArticleEntity;
import java.util.List;

public interface KbArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kb_articles
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int deleteByPrimaryKey(String kbArticleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kb_articles
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int insert(KbArticleEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kb_articles
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    KbArticleEntity selectByPrimaryKey(String kbArticleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kb_articles
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    List<KbArticleEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kb_articles
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int updateByPrimaryKey(KbArticleEntity row);
}