package com.sme.be_sme.modules.knowledge.infrastructure.mapper;

import com.sme.be_sme.modules.knowledge.infrastructure.persistence.entity.TagEntity;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(TagEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    TagEntity selectByPrimaryKey(String tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<TagEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tags
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(TagEntity row);
}