package com.sme.be_sme.modules.company.infrastructure.persistence.entity;

import java.util.Date;

public class CompanyEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companies.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companies.name
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companies.tax_code
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String taxCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companies.address
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companies.timezone
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String timezone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companies.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companies.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companies.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companies.company_id
     *
     * @return the value of companies.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companies.company_id
     *
     * @param companyId the value for companies.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companies.name
     *
     * @return the value of companies.name
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companies.name
     *
     * @param name the value for companies.name
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companies.tax_code
     *
     * @return the value of companies.tax_code
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getTaxCode() {
        return taxCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companies.tax_code
     *
     * @param taxCode the value for companies.tax_code
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setTaxCode(String taxCode) {
        this.taxCode = taxCode == null ? null : taxCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companies.address
     *
     * @return the value of companies.address
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companies.address
     *
     * @param address the value for companies.address
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companies.timezone
     *
     * @return the value of companies.timezone
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getTimezone() {
        return timezone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companies.timezone
     *
     * @param timezone the value for companies.timezone
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setTimezone(String timezone) {
        this.timezone = timezone == null ? null : timezone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companies.status
     *
     * @return the value of companies.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companies.status
     *
     * @param status the value for companies.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companies.created_at
     *
     * @return the value of companies.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companies.created_at
     *
     * @param createdAt the value for companies.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companies.updated_at
     *
     * @return the value of companies.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companies.updated_at
     *
     * @param updatedAt the value for companies.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}