package com.sme.be_sme.modules.company.infrastructure.persistence.entity;

import java.util.Date;

public class DepartmentEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.department_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.name
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.type
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.updated_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.department_id
     *
     * @return the value of departments.department_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.department_id
     *
     * @param departmentId the value for departments.department_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.company_id
     *
     * @return the value of departments.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.company_id
     *
     * @param companyId the value for departments.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.name
     *
     * @return the value of departments.name
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.name
     *
     * @param name the value for departments.name
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.type
     *
     * @return the value of departments.type
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.type
     *
     * @param type the value for departments.type
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.status
     *
     * @return the value of departments.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.status
     *
     * @param status the value for departments.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.created_at
     *
     * @return the value of departments.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.created_at
     *
     * @param createdAt the value for departments.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.updated_at
     *
     * @return the value of departments.updated_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.updated_at
     *
     * @param updatedAt the value for departments.updated_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}