package com.sme.be_sme.modules.identity.infrastructure.persistence.entity;

import java.util.Date;

public class PermissionEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.permission_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.code
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.description
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.permission_id
     *
     * @return the value of permissions.permission_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.permission_id
     *
     * @param permissionId the value for permissions.permission_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId == null ? null : permissionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.company_id
     *
     * @return the value of permissions.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.company_id
     *
     * @param companyId the value for permissions.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.code
     *
     * @return the value of permissions.code
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.code
     *
     * @param code the value for permissions.code
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.description
     *
     * @return the value of permissions.description
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.description
     *
     * @param description the value for permissions.description
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.status
     *
     * @return the value of permissions.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.status
     *
     * @param status the value for permissions.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.created_at
     *
     * @return the value of permissions.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.created_at
     *
     * @param createdAt the value for permissions.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.updated_at
     *
     * @return the value of permissions.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.updated_at
     *
     * @param updatedAt the value for permissions.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}