package com.sme.be_sme.modules.identity.infrastructure.persistence.entity;

import java.util.Date;

public class RolePermissionEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.role_permission_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String rolePermissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.role_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.permission_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permissions.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.role_permission_id
     *
     * @return the value of role_permissions.role_permission_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getRolePermissionId() {
        return rolePermissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.role_permission_id
     *
     * @param rolePermissionId the value for role_permissions.role_permission_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setRolePermissionId(String rolePermissionId) {
        this.rolePermissionId = rolePermissionId == null ? null : rolePermissionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.company_id
     *
     * @return the value of role_permissions.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.company_id
     *
     * @param companyId the value for role_permissions.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.role_id
     *
     * @return the value of role_permissions.role_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.role_id
     *
     * @param roleId the value for role_permissions.role_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.permission_id
     *
     * @return the value of role_permissions.permission_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.permission_id
     *
     * @param permissionId the value for role_permissions.permission_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId == null ? null : permissionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permissions.created_at
     *
     * @return the value of role_permissions.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permissions.created_at
     *
     * @param createdAt the value for role_permissions.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}