package com.sme.be_sme.modules.identity.infrastructure.persistence.entity;

import java.util.Date;

public class UserRoleEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.user_role_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String userRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.user_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.role_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    private Date updatedAt;

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.user_role_id
     *
     * @return the value of user_roles.user_role_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.user_role_id
     *
     * @param userRoleId the value for user_roles.user_role_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setUserRoleId(String userRoleId) {
        this.userRoleId = userRoleId == null ? null : userRoleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.company_id
     *
     * @return the value of user_roles.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.company_id
     *
     * @param companyId the value for user_roles.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.user_id
     *
     * @return the value of user_roles.user_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.user_id
     *
     * @param userId the value for user_roles.user_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.role_id
     *
     * @return the value of user_roles.role_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.role_id
     *
     * @param roleId the value for user_roles.role_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.created_at
     *
     * @return the value of user_roles.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.created_at
     *
     * @param createdAt the value for user_roles.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}