package com.sme.be_sme.modules.billing.infrastructure.persistence.entity;

import java.math.BigDecimal;
import java.util.Date;

public class DiscountCodeEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_codes.discount_code_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String discountCodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_codes.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_codes.code
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_codes.description
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_codes.discount_type
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String discountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_codes.discount_value
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private BigDecimal discountValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_codes.max_redemptions
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Integer maxRedemptions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_codes.redeemed_count
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Integer redeemedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_codes.valid_from
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date validFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_codes.valid_to
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date validTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_codes.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_codes.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_codes.discount_code_id
     *
     * @return the value of discount_codes.discount_code_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getDiscountCodeId() {
        return discountCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_codes.discount_code_id
     *
     * @param discountCodeId the value for discount_codes.discount_code_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setDiscountCodeId(String discountCodeId) {
        this.discountCodeId = discountCodeId == null ? null : discountCodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_codes.company_id
     *
     * @return the value of discount_codes.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_codes.company_id
     *
     * @param companyId the value for discount_codes.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_codes.code
     *
     * @return the value of discount_codes.code
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_codes.code
     *
     * @param code the value for discount_codes.code
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_codes.description
     *
     * @return the value of discount_codes.description
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_codes.description
     *
     * @param description the value for discount_codes.description
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_codes.discount_type
     *
     * @return the value of discount_codes.discount_type
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getDiscountType() {
        return discountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_codes.discount_type
     *
     * @param discountType the value for discount_codes.discount_type
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setDiscountType(String discountType) {
        this.discountType = discountType == null ? null : discountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_codes.discount_value
     *
     * @return the value of discount_codes.discount_value
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public BigDecimal getDiscountValue() {
        return discountValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_codes.discount_value
     *
     * @param discountValue the value for discount_codes.discount_value
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setDiscountValue(BigDecimal discountValue) {
        this.discountValue = discountValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_codes.max_redemptions
     *
     * @return the value of discount_codes.max_redemptions
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Integer getMaxRedemptions() {
        return maxRedemptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_codes.max_redemptions
     *
     * @param maxRedemptions the value for discount_codes.max_redemptions
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setMaxRedemptions(Integer maxRedemptions) {
        this.maxRedemptions = maxRedemptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_codes.redeemed_count
     *
     * @return the value of discount_codes.redeemed_count
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Integer getRedeemedCount() {
        return redeemedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_codes.redeemed_count
     *
     * @param redeemedCount the value for discount_codes.redeemed_count
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setRedeemedCount(Integer redeemedCount) {
        this.redeemedCount = redeemedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_codes.valid_from
     *
     * @return the value of discount_codes.valid_from
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getValidFrom() {
        return validFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_codes.valid_from
     *
     * @param validFrom the value for discount_codes.valid_from
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setValidFrom(Date validFrom) {
        this.validFrom = validFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_codes.valid_to
     *
     * @return the value of discount_codes.valid_to
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getValidTo() {
        return validTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_codes.valid_to
     *
     * @param validTo the value for discount_codes.valid_to
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setValidTo(Date validTo) {
        this.validTo = validTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_codes.status
     *
     * @return the value of discount_codes.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_codes.status
     *
     * @param status the value for discount_codes.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_codes.created_at
     *
     * @return the value of discount_codes.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_codes.created_at
     *
     * @param createdAt the value for discount_codes.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}