package com.sme.be_sme.modules.billing.infrastructure.persistence.entity;

import java.util.Date;

public class DunningCaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dunning_cases.dunning_case_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String dunningCaseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dunning_cases.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dunning_cases.subscription_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String subscriptionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dunning_cases.retry_count
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Integer retryCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dunning_cases.next_retry_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date nextRetryAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dunning_cases.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dunning_cases.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dunning_cases.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dunning_cases.dunning_case_id
     *
     * @return the value of dunning_cases.dunning_case_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getDunningCaseId() {
        return dunningCaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dunning_cases.dunning_case_id
     *
     * @param dunningCaseId the value for dunning_cases.dunning_case_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setDunningCaseId(String dunningCaseId) {
        this.dunningCaseId = dunningCaseId == null ? null : dunningCaseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dunning_cases.company_id
     *
     * @return the value of dunning_cases.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dunning_cases.company_id
     *
     * @param companyId the value for dunning_cases.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dunning_cases.subscription_id
     *
     * @return the value of dunning_cases.subscription_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getSubscriptionId() {
        return subscriptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dunning_cases.subscription_id
     *
     * @param subscriptionId the value for dunning_cases.subscription_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setSubscriptionId(String subscriptionId) {
        this.subscriptionId = subscriptionId == null ? null : subscriptionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dunning_cases.retry_count
     *
     * @return the value of dunning_cases.retry_count
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Integer getRetryCount() {
        return retryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dunning_cases.retry_count
     *
     * @param retryCount the value for dunning_cases.retry_count
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setRetryCount(Integer retryCount) {
        this.retryCount = retryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dunning_cases.next_retry_at
     *
     * @return the value of dunning_cases.next_retry_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getNextRetryAt() {
        return nextRetryAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dunning_cases.next_retry_at
     *
     * @param nextRetryAt the value for dunning_cases.next_retry_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setNextRetryAt(Date nextRetryAt) {
        this.nextRetryAt = nextRetryAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dunning_cases.status
     *
     * @return the value of dunning_cases.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dunning_cases.status
     *
     * @param status the value for dunning_cases.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dunning_cases.created_at
     *
     * @return the value of dunning_cases.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dunning_cases.created_at
     *
     * @param createdAt the value for dunning_cases.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dunning_cases.updated_at
     *
     * @return the value of dunning_cases.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dunning_cases.updated_at
     *
     * @param updatedAt the value for dunning_cases.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}