package com.sme.be_sme.modules.billing.infrastructure.persistence.entity;

import java.util.Date;

public class PlanEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plans.plan_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String planId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plans.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plans.code
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plans.name
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plans.employee_limit_per_month
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Integer employeeLimitPerMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plans.price_vnd_monthly
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Integer priceVndMonthly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plans.price_vnd_yearly
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Integer priceVndYearly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plans.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plans.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plans.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plans.plan_id
     *
     * @return the value of plans.plan_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plans.plan_id
     *
     * @param planId the value for plans.plan_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setPlanId(String planId) {
        this.planId = planId == null ? null : planId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plans.company_id
     *
     * @return the value of plans.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plans.company_id
     *
     * @param companyId the value for plans.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plans.code
     *
     * @return the value of plans.code
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plans.code
     *
     * @param code the value for plans.code
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plans.name
     *
     * @return the value of plans.name
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plans.name
     *
     * @param name the value for plans.name
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plans.employee_limit_per_month
     *
     * @return the value of plans.employee_limit_per_month
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Integer getEmployeeLimitPerMonth() {
        return employeeLimitPerMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plans.employee_limit_per_month
     *
     * @param employeeLimitPerMonth the value for plans.employee_limit_per_month
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setEmployeeLimitPerMonth(Integer employeeLimitPerMonth) {
        this.employeeLimitPerMonth = employeeLimitPerMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plans.price_vnd_monthly
     *
     * @return the value of plans.price_vnd_monthly
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Integer getPriceVndMonthly() {
        return priceVndMonthly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plans.price_vnd_monthly
     *
     * @param priceVndMonthly the value for plans.price_vnd_monthly
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setPriceVndMonthly(Integer priceVndMonthly) {
        this.priceVndMonthly = priceVndMonthly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plans.price_vnd_yearly
     *
     * @return the value of plans.price_vnd_yearly
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Integer getPriceVndYearly() {
        return priceVndYearly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plans.price_vnd_yearly
     *
     * @param priceVndYearly the value for plans.price_vnd_yearly
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setPriceVndYearly(Integer priceVndYearly) {
        this.priceVndYearly = priceVndYearly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plans.status
     *
     * @return the value of plans.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plans.status
     *
     * @param status the value for plans.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plans.created_at
     *
     * @return the value of plans.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plans.created_at
     *
     * @param createdAt the value for plans.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plans.updated_at
     *
     * @return the value of plans.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plans.updated_at
     *
     * @param updatedAt the value for plans.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}