package com.sme.be_sme.modules.billing.infrastructure.persistence.entity;

import java.util.Date;

public class PlanFeatureEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_features.plan_feature_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String planFeatureId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_features.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_features.plan_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String planId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_features.feature_code
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String featureCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_features.enabled
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_features.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_features.plan_feature_id
     *
     * @return the value of plan_features.plan_feature_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getPlanFeatureId() {
        return planFeatureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_features.plan_feature_id
     *
     * @param planFeatureId the value for plan_features.plan_feature_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setPlanFeatureId(String planFeatureId) {
        this.planFeatureId = planFeatureId == null ? null : planFeatureId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_features.company_id
     *
     * @return the value of plan_features.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_features.company_id
     *
     * @param companyId the value for plan_features.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_features.plan_id
     *
     * @return the value of plan_features.plan_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_features.plan_id
     *
     * @param planId the value for plan_features.plan_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setPlanId(String planId) {
        this.planId = planId == null ? null : planId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_features.feature_code
     *
     * @return the value of plan_features.feature_code
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getFeatureCode() {
        return featureCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_features.feature_code
     *
     * @param featureCode the value for plan_features.feature_code
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setFeatureCode(String featureCode) {
        this.featureCode = featureCode == null ? null : featureCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_features.enabled
     *
     * @return the value of plan_features.enabled
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_features.enabled
     *
     * @param enabled the value for plan_features.enabled
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_features.created_at
     *
     * @return the value of plan_features.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_features.created_at
     *
     * @param createdAt the value for plan_features.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}