package com.sme.be_sme.modules.document.infrastructure.mapper;

import com.sme.be_sme.modules.document.infrastructure.persistence.entity.DocumentAccessRuleEntity;
import java.util.List;

public interface DocumentAccessRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_access_rules
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String documentAccessRuleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_access_rules
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(DocumentAccessRuleEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_access_rules
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    DocumentAccessRuleEntity selectByPrimaryKey(String documentAccessRuleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_access_rules
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<DocumentAccessRuleEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_access_rules
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(DocumentAccessRuleEntity row);
}