package com.sme.be_sme.modules.document.infrastructure.mapper;

import com.sme.be_sme.modules.document.infrastructure.persistence.entity.DocumentEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface DocumentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documents
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String documentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documents
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(DocumentEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documents
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    DocumentEntity selectByPrimaryKey(String documentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documents
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<DocumentEntity> selectAll();

    List<DocumentEntity> selectByCompanyId(@Param("companyId") String companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documents
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(DocumentEntity row);
}