package com.sme.be_sme.modules.document.infrastructure.mapper;

import com.sme.be_sme.modules.document.infrastructure.persistence.entity.DocumentAcknowledgementEntity;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface DocumentAcknowledgementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_acknowledgements
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String documentAcknowledgementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_acknowledgements
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(DocumentAcknowledgementEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_acknowledgements
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    DocumentAcknowledgementEntity selectByPrimaryKey(String documentAcknowledgementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_acknowledgements
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<DocumentAcknowledgementEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_acknowledgements
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(DocumentAcknowledgementEntity row);
}