package com.sme.be_sme.modules.document.infrastructure.mapper;

import com.sme.be_sme.modules.document.infrastructure.persistence.entity.DocumentCategoryEntity;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface DocumentCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_categories
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String documentCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_categories
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(DocumentCategoryEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_categories
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    DocumentCategoryEntity selectByPrimaryKey(String documentCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_categories
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<DocumentCategoryEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_categories
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(DocumentCategoryEntity row);
}