package com.sme.be_sme.modules.document.infrastructure.mapper;

import com.sme.be_sme.modules.document.infrastructure.persistence.entity.DocumentEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface DocumentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documents
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String documentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documents
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(DocumentEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documents
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    DocumentEntity selectByPrimaryKey(String documentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documents
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<DocumentEntity> selectAll();

    List<DocumentEntity> selectByCompanyId(@Param("companyId") String companyId);

    long countByCompanyId(@Param("companyId") String companyId);

    List<DocumentEntity> selectByCompanyIdAndContentKind(
            @Param("companyId") String companyId,
            @Param("contentKind") String contentKind);

    long countEditorDocumentsHrPaged(
            @Param("companyId") String companyId,
            @Param("contentKind") String contentKind,
            @Param("titleQuery") String titleQuery);

    List<DocumentEntity> selectEditorDocumentsHrPaged(
            @Param("companyId") String companyId,
            @Param("contentKind") String contentKind,
            @Param("titleQuery") String titleQuery,
            @Param("limit") int limit,
            @Param("offset") int offset);

    long countEditorDocumentsAccessiblePaged(
            @Param("companyId") String companyId,
            @Param("contentKind") String contentKind,
            @Param("titleQuery") String titleQuery,
            @Param("roleIds") List<String> roleIds,
            @Param("departmentId") String departmentId);

    List<DocumentEntity> selectEditorDocumentsAccessiblePaged(
            @Param("companyId") String companyId,
            @Param("contentKind") String contentKind,
            @Param("titleQuery") String titleQuery,
            @Param("roleIds") List<String> roleIds,
            @Param("departmentId") String departmentId,
            @Param("limit") int limit,
            @Param("offset") int offset);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documents
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(DocumentEntity row);
}