package com.sme.be_sme.modules.automation.infrastructure.mapper;

import com.sme.be_sme.modules.automation.infrastructure.persistence.entity.EmailCampaignEntity;
import java.util.List;

public interface EmailCampaignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_campaigns
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int deleteByPrimaryKey(String emailCampaignId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_campaigns
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int insert(EmailCampaignEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_campaigns
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    EmailCampaignEntity selectByPrimaryKey(String emailCampaignId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_campaigns
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    List<EmailCampaignEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_campaigns
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int updateByPrimaryKey(EmailCampaignEntity row);
}