package com.sme.be_sme.modules.automation.infrastructure.mapper;

import com.sme.be_sme.modules.automation.infrastructure.persistence.entity.EmailTemplateEntity;
import java.util.List;

public interface EmailTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_templates
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int deleteByPrimaryKey(String emailTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_templates
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int insert(EmailTemplateEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_templates
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    EmailTemplateEntity selectByPrimaryKey(String emailTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_templates
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    List<EmailTemplateEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_templates
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int updateByPrimaryKey(EmailTemplateEntity row);
}