package com.sme.be_sme.modules.automation.infrastructure.mapper;

import com.sme.be_sme.modules.automation.infrastructure.persistence.entity.EmailLogEntity;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface EmailLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_logs
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String emailLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_logs
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(EmailLogEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_logs
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    EmailLogEntity selectByPrimaryKey(String emailLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_logs
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<EmailLogEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_logs
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(EmailLogEntity row);
}