package com.sme.be_sme.modules.survey.infrastructure.mapper;

import com.sme.be_sme.modules.survey.infrastructure.persistence.entity.SurveyResponseEntity;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SurveyResponseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_responses
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String surveyResponseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_responses
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(SurveyResponseEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_responses
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    SurveyResponseEntity selectByPrimaryKey(String surveyResponseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_responses
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<SurveyResponseEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_responses
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(SurveyResponseEntity row);
}