package com.sme.be_sme.modules.survey.infrastructure.mapper;

import com.sme.be_sme.modules.survey.infrastructure.persistence.entity.SurveyTemplateEntity;
import java.util.List;

public interface SurveyTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_templates
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int deleteByPrimaryKey(String surveyTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_templates
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int insert(SurveyTemplateEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_templates
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    SurveyTemplateEntity selectByPrimaryKey(String surveyTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_templates
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    List<SurveyTemplateEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_templates
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int updateByPrimaryKey(SurveyTemplateEntity row);
}