package com.sme.be_sme.modules.survey.infrastructure.mapper;

import com.sme.be_sme.modules.survey.infrastructure.persistence.entity.SurveyTemplateEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface SurveyTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_templates
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String surveyTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_templates
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(SurveyTemplateEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_templates
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    SurveyTemplateEntity selectByPrimaryKey(String surveyTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_templates
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<SurveyTemplateEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_templates
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(SurveyTemplateEntity row);

    SurveyTemplateEntity findActiveDefaultByCompanyStageAndTargetRoleExcludingTemplateId(
            @org.apache.ibatis.annotations.Param("companyId") String companyId,
            @org.apache.ibatis.annotations.Param("stage") String stage,
            @org.apache.ibatis.annotations.Param("targetRole") String targetRole,
            @org.apache.ibatis.annotations.Param("excludeTemplateId") String excludeTemplateId
    );
    SurveyTemplateEntity findActiveDefaultByCompanyStageAndTargetRole(
            @org.apache.ibatis.annotations.Param("companyId") String companyId,
            @org.apache.ibatis.annotations.Param("stage") String stage,
            @org.apache.ibatis.annotations.Param("targetRole") String targetRole
    );
}