package com.sme.be_sme.modules.survey.infrastructure.mapper;

import com.sme.be_sme.modules.survey.infrastructure.persistence.entity.SurveyQuestionEntity;
import java.util.List;

public interface SurveyQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_questions
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String surveyQuestionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_questions
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(SurveyQuestionEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_questions
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    SurveyQuestionEntity selectByPrimaryKey(String surveyQuestionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_questions
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<SurveyQuestionEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_questions
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(SurveyQuestionEntity row);
}