package com.sme.be_sme.modules.survey.infrastructure.mapper;

import com.sme.be_sme.modules.survey.infrastructure.persistence.entity.SurveyAnswerEntity;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SurveyAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_answers
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String surveyAnswerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_answers
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(SurveyAnswerEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_answers
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    SurveyAnswerEntity selectByPrimaryKey(String surveyAnswerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_answers
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<SurveyAnswerEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table survey_answers
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(SurveyAnswerEntity row);
}