package com.sme.be_sme.modules.knowledge.infrastructure.persistence.entity;

import java.util.Date;

public class ChatMessageEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_messages.chat_message_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String chatMessageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_messages.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_messages.chat_session_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String chatSessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_messages.sender
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_messages.content
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_messages.kb_article_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String kbArticleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_messages.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_messages.chat_message_id
     *
     * @return the value of chat_messages.chat_message_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getChatMessageId() {
        return chatMessageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_messages.chat_message_id
     *
     * @param chatMessageId the value for chat_messages.chat_message_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setChatMessageId(String chatMessageId) {
        this.chatMessageId = chatMessageId == null ? null : chatMessageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_messages.company_id
     *
     * @return the value of chat_messages.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_messages.company_id
     *
     * @param companyId the value for chat_messages.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_messages.chat_session_id
     *
     * @return the value of chat_messages.chat_session_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getChatSessionId() {
        return chatSessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_messages.chat_session_id
     *
     * @param chatSessionId the value for chat_messages.chat_session_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setChatSessionId(String chatSessionId) {
        this.chatSessionId = chatSessionId == null ? null : chatSessionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_messages.sender
     *
     * @return the value of chat_messages.sender
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_messages.sender
     *
     * @param sender the value for chat_messages.sender
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setSender(String sender) {
        this.sender = sender == null ? null : sender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_messages.content
     *
     * @return the value of chat_messages.content
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_messages.content
     *
     * @param content the value for chat_messages.content
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_messages.kb_article_id
     *
     * @return the value of chat_messages.kb_article_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getKbArticleId() {
        return kbArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_messages.kb_article_id
     *
     * @param kbArticleId the value for chat_messages.kb_article_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setKbArticleId(String kbArticleId) {
        this.kbArticleId = kbArticleId == null ? null : kbArticleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_messages.created_at
     *
     * @return the value of chat_messages.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_messages.created_at
     *
     * @param createdAt the value for chat_messages.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}