package com.sme.be_sme.modules.knowledge.infrastructure.persistence.entity;

import java.util.Date;

public class ChatSessionEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_sessions.chat_session_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String chatSessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_sessions.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_sessions.user_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_sessions.channel
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_sessions.started_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date startedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_sessions.ended_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date endedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_sessions.chat_session_id
     *
     * @return the value of chat_sessions.chat_session_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getChatSessionId() {
        return chatSessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_sessions.chat_session_id
     *
     * @param chatSessionId the value for chat_sessions.chat_session_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setChatSessionId(String chatSessionId) {
        this.chatSessionId = chatSessionId == null ? null : chatSessionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_sessions.company_id
     *
     * @return the value of chat_sessions.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_sessions.company_id
     *
     * @param companyId the value for chat_sessions.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_sessions.user_id
     *
     * @return the value of chat_sessions.user_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_sessions.user_id
     *
     * @param userId the value for chat_sessions.user_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_sessions.channel
     *
     * @return the value of chat_sessions.channel
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_sessions.channel
     *
     * @param channel the value for chat_sessions.channel
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_sessions.started_at
     *
     * @return the value of chat_sessions.started_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getStartedAt() {
        return startedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_sessions.started_at
     *
     * @param startedAt the value for chat_sessions.started_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setStartedAt(Date startedAt) {
        this.startedAt = startedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_sessions.ended_at
     *
     * @return the value of chat_sessions.ended_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getEndedAt() {
        return endedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_sessions.ended_at
     *
     * @param endedAt the value for chat_sessions.ended_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setEndedAt(Date endedAt) {
        this.endedAt = endedAt;
    }
}