package com.sme.be_sme.modules.knowledge.infrastructure.persistence.entity;

import java.util.Date;

public class KbArticleTagEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kb_article_tags.kb_article_tag_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String kbArticleTagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kb_article_tags.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kb_article_tags.kb_article_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String kbArticleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kb_article_tags.tag_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String tagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kb_article_tags.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kb_article_tags.kb_article_tag_id
     *
     * @return the value of kb_article_tags.kb_article_tag_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getKbArticleTagId() {
        return kbArticleTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kb_article_tags.kb_article_tag_id
     *
     * @param kbArticleTagId the value for kb_article_tags.kb_article_tag_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setKbArticleTagId(String kbArticleTagId) {
        this.kbArticleTagId = kbArticleTagId == null ? null : kbArticleTagId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kb_article_tags.company_id
     *
     * @return the value of kb_article_tags.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kb_article_tags.company_id
     *
     * @param companyId the value for kb_article_tags.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kb_article_tags.kb_article_id
     *
     * @return the value of kb_article_tags.kb_article_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getKbArticleId() {
        return kbArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kb_article_tags.kb_article_id
     *
     * @param kbArticleId the value for kb_article_tags.kb_article_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setKbArticleId(String kbArticleId) {
        this.kbArticleId = kbArticleId == null ? null : kbArticleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kb_article_tags.tag_id
     *
     * @return the value of kb_article_tags.tag_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kb_article_tags.tag_id
     *
     * @param tagId the value for kb_article_tags.tag_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setTagId(String tagId) {
        this.tagId = tagId == null ? null : tagId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kb_article_tags.created_at
     *
     * @return the value of kb_article_tags.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kb_article_tags.created_at
     *
     * @param createdAt the value for kb_article_tags.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}