package com.sme.be_sme.modules.employee.infrastructure.persistence.entity;

import java.util.Date;

public class EmployeeProfileEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_profiles.employee_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_profiles.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_profiles.user_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_profiles.employee_code
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String employeeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_profiles.employee_name
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String employeeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_profiles.employee_email
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String employeeEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_profiles.employee_phone
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String employeePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_profiles.job_title
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String jobTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_profiles.manager_user_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String managerUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_profiles.department_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_profiles.start_date
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_profiles.work_location
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String workLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_profiles.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_profiles.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_profiles.updated_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_profiles.employee_id
     *
     * @return the value of employee_profiles.employee_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_profiles.employee_id
     *
     * @param employeeId the value for employee_profiles.employee_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_profiles.company_id
     *
     * @return the value of employee_profiles.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_profiles.company_id
     *
     * @param companyId the value for employee_profiles.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_profiles.user_id
     *
     * @return the value of employee_profiles.user_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_profiles.user_id
     *
     * @param userId the value for employee_profiles.user_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_profiles.employee_code
     *
     * @return the value of employee_profiles.employee_code
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getEmployeeCode() {
        return employeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_profiles.employee_code
     *
     * @param employeeCode the value for employee_profiles.employee_code
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode == null ? null : employeeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_profiles.employee_name
     *
     * @return the value of employee_profiles.employee_name
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_profiles.employee_name
     *
     * @param employeeName the value for employee_profiles.employee_name
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_profiles.employee_email
     *
     * @return the value of employee_profiles.employee_email
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getEmployeeEmail() {
        return employeeEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_profiles.employee_email
     *
     * @param employeeEmail the value for employee_profiles.employee_email
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setEmployeeEmail(String employeeEmail) {
        this.employeeEmail = employeeEmail == null ? null : employeeEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_profiles.employee_phone
     *
     * @return the value of employee_profiles.employee_phone
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getEmployeePhone() {
        return employeePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_profiles.employee_phone
     *
     * @param employeePhone the value for employee_profiles.employee_phone
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setEmployeePhone(String employeePhone) {
        this.employeePhone = employeePhone == null ? null : employeePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_profiles.job_title
     *
     * @return the value of employee_profiles.job_title
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_profiles.job_title
     *
     * @param jobTitle the value for employee_profiles.job_title
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle == null ? null : jobTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_profiles.manager_user_id
     *
     * @return the value of employee_profiles.manager_user_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getManagerUserId() {
        return managerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_profiles.manager_user_id
     *
     * @param managerUserId the value for employee_profiles.manager_user_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setManagerUserId(String managerUserId) {
        this.managerUserId = managerUserId == null ? null : managerUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_profiles.department_id
     *
     * @return the value of employee_profiles.department_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_profiles.department_id
     *
     * @param departmentId the value for employee_profiles.department_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_profiles.start_date
     *
     * @return the value of employee_profiles.start_date
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_profiles.start_date
     *
     * @param startDate the value for employee_profiles.start_date
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_profiles.work_location
     *
     * @return the value of employee_profiles.work_location
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getWorkLocation() {
        return workLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_profiles.work_location
     *
     * @param workLocation the value for employee_profiles.work_location
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setWorkLocation(String workLocation) {
        this.workLocation = workLocation == null ? null : workLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_profiles.status
     *
     * @return the value of employee_profiles.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_profiles.status
     *
     * @param status the value for employee_profiles.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_profiles.created_at
     *
     * @return the value of employee_profiles.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_profiles.created_at
     *
     * @param createdAt the value for employee_profiles.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_profiles.updated_at
     *
     * @return the value of employee_profiles.updated_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_profiles.updated_at
     *
     * @param updatedAt the value for employee_profiles.updated_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}