package com.sme.be_sme.modules.notification.infrastructure.mapper;

import com.sme.be_sme.modules.notification.infrastructure.persistence.entity.NotificationEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

@Mapper
public interface NotificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String notificationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(NotificationEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    NotificationEntity selectByPrimaryKey(String notificationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<NotificationEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(NotificationEntity row);

    List<NotificationEntity> selectByCompanyIdAndUserId(
            @Param("companyId") String companyId,
            @Param("userId") String userId,
            @Param("unreadOnly") Boolean unreadOnly,
            @Param("offset") int offset,
            @Param("limit") int limit);

    int countByCompanyIdAndUserId(
            @Param("companyId") String companyId,
            @Param("userId") String userId,
            @Param("unreadOnly") Boolean unreadOnly);

    int updateReadAtByIds(@Param("notificationIds") List<String> notificationIds, @Param("readAt") Date readAt);
}