package com.sme.be_sme.modules.document.infrastructure.persistence.entity;

import java.util.Date;

public class DocumentEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documents.document_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String documentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documents.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documents.document_category_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String documentCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documents.title
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documents.description
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documents.visibility
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String visibility;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documents.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documents.created_by
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documents.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column documents.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documents.document_id
     *
     * @return the value of documents.document_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documents.document_id
     *
     * @param documentId the value for documents.document_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setDocumentId(String documentId) {
        this.documentId = documentId == null ? null : documentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documents.company_id
     *
     * @return the value of documents.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documents.company_id
     *
     * @param companyId the value for documents.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documents.document_category_id
     *
     * @return the value of documents.document_category_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getDocumentCategoryId() {
        return documentCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documents.document_category_id
     *
     * @param documentCategoryId the value for documents.document_category_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setDocumentCategoryId(String documentCategoryId) {
        this.documentCategoryId = documentCategoryId == null ? null : documentCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documents.title
     *
     * @return the value of documents.title
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documents.title
     *
     * @param title the value for documents.title
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documents.description
     *
     * @return the value of documents.description
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documents.description
     *
     * @param description the value for documents.description
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documents.visibility
     *
     * @return the value of documents.visibility
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getVisibility() {
        return visibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documents.visibility
     *
     * @param visibility the value for documents.visibility
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setVisibility(String visibility) {
        this.visibility = visibility == null ? null : visibility.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documents.status
     *
     * @return the value of documents.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documents.status
     *
     * @param status the value for documents.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documents.created_by
     *
     * @return the value of documents.created_by
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documents.created_by
     *
     * @param createdBy the value for documents.created_by
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documents.created_at
     *
     * @return the value of documents.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documents.created_at
     *
     * @param createdAt the value for documents.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documents.updated_at
     *
     * @return the value of documents.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documents.updated_at
     *
     * @param updatedAt the value for documents.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}