package com.sme.be_sme.modules.document.infrastructure.persistence.entity;

import java.util.Date;

public class DocumentAcknowledgementEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_acknowledgements.document_acknowledgement_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String documentAcknowledgementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_acknowledgements.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_acknowledgements.document_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String documentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_acknowledgements.user_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_acknowledgements.onboarding_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String onboardingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_acknowledgements.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_acknowledgements.read_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date readAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_acknowledgements.acked_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date ackedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_acknowledgements.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_acknowledgements.document_acknowledgement_id
     *
     * @return the value of document_acknowledgements.document_acknowledgement_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getDocumentAcknowledgementId() {
        return documentAcknowledgementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_acknowledgements.document_acknowledgement_id
     *
     * @param documentAcknowledgementId the value for document_acknowledgements.document_acknowledgement_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setDocumentAcknowledgementId(String documentAcknowledgementId) {
        this.documentAcknowledgementId = documentAcknowledgementId == null ? null : documentAcknowledgementId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_acknowledgements.company_id
     *
     * @return the value of document_acknowledgements.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_acknowledgements.company_id
     *
     * @param companyId the value for document_acknowledgements.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_acknowledgements.document_id
     *
     * @return the value of document_acknowledgements.document_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_acknowledgements.document_id
     *
     * @param documentId the value for document_acknowledgements.document_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setDocumentId(String documentId) {
        this.documentId = documentId == null ? null : documentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_acknowledgements.user_id
     *
     * @return the value of document_acknowledgements.user_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_acknowledgements.user_id
     *
     * @param userId the value for document_acknowledgements.user_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_acknowledgements.onboarding_id
     *
     * @return the value of document_acknowledgements.onboarding_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getOnboardingId() {
        return onboardingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_acknowledgements.onboarding_id
     *
     * @param onboardingId the value for document_acknowledgements.onboarding_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setOnboardingId(String onboardingId) {
        this.onboardingId = onboardingId == null ? null : onboardingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_acknowledgements.status
     *
     * @return the value of document_acknowledgements.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_acknowledgements.status
     *
     * @param status the value for document_acknowledgements.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_acknowledgements.read_at
     *
     * @return the value of document_acknowledgements.read_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getReadAt() {
        return readAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_acknowledgements.read_at
     *
     * @param readAt the value for document_acknowledgements.read_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setReadAt(Date readAt) {
        this.readAt = readAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_acknowledgements.acked_at
     *
     * @return the value of document_acknowledgements.acked_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getAckedAt() {
        return ackedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_acknowledgements.acked_at
     *
     * @param ackedAt the value for document_acknowledgements.acked_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setAckedAt(Date ackedAt) {
        this.ackedAt = ackedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_acknowledgements.created_at
     *
     * @return the value of document_acknowledgements.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_acknowledgements.created_at
     *
     * @param createdAt the value for document_acknowledgements.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}