package com.sme.be_sme.modules.document.infrastructure.persistence.entity;

import java.util.Date;

public class DocumentVersionEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_versions.document_version_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String documentVersionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_versions.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_versions.document_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String documentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_versions.version_no
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Integer versionNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_versions.file_url
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_versions.file_name
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_versions.file_type
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_versions.file_size_bytes
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Long fileSizeBytes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_versions.uploaded_by
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String uploadedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_versions.uploaded_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date uploadedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_versions.document_version_id
     *
     * @return the value of document_versions.document_version_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getDocumentVersionId() {
        return documentVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_versions.document_version_id
     *
     * @param documentVersionId the value for document_versions.document_version_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setDocumentVersionId(String documentVersionId) {
        this.documentVersionId = documentVersionId == null ? null : documentVersionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_versions.company_id
     *
     * @return the value of document_versions.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_versions.company_id
     *
     * @param companyId the value for document_versions.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_versions.document_id
     *
     * @return the value of document_versions.document_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_versions.document_id
     *
     * @param documentId the value for document_versions.document_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setDocumentId(String documentId) {
        this.documentId = documentId == null ? null : documentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_versions.version_no
     *
     * @return the value of document_versions.version_no
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Integer getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_versions.version_no
     *
     * @param versionNo the value for document_versions.version_no
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_versions.file_url
     *
     * @return the value of document_versions.file_url
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_versions.file_url
     *
     * @param fileUrl the value for document_versions.file_url
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_versions.file_name
     *
     * @return the value of document_versions.file_name
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_versions.file_name
     *
     * @param fileName the value for document_versions.file_name
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_versions.file_type
     *
     * @return the value of document_versions.file_type
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_versions.file_type
     *
     * @param fileType the value for document_versions.file_type
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_versions.file_size_bytes
     *
     * @return the value of document_versions.file_size_bytes
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Long getFileSizeBytes() {
        return fileSizeBytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_versions.file_size_bytes
     *
     * @param fileSizeBytes the value for document_versions.file_size_bytes
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setFileSizeBytes(Long fileSizeBytes) {
        this.fileSizeBytes = fileSizeBytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_versions.uploaded_by
     *
     * @return the value of document_versions.uploaded_by
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getUploadedBy() {
        return uploadedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_versions.uploaded_by
     *
     * @param uploadedBy the value for document_versions.uploaded_by
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setUploadedBy(String uploadedBy) {
        this.uploadedBy = uploadedBy == null ? null : uploadedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_versions.uploaded_at
     *
     * @return the value of document_versions.uploaded_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getUploadedAt() {
        return uploadedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_versions.uploaded_at
     *
     * @param uploadedAt the value for document_versions.uploaded_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setUploadedAt(Date uploadedAt) {
        this.uploadedAt = uploadedAt;
    }
}