package com.sme.be_sme.modules.document.infrastructure.persistence.entity;

import java.util.Date;

public class DocumentAccessRuleEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_access_rules.document_access_rule_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String documentAccessRuleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_access_rules.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_access_rules.document_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String documentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_access_rules.role_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_access_rules.department_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_access_rules.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_access_rules.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_access_rules.document_access_rule_id
     *
     * @return the value of document_access_rules.document_access_rule_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getDocumentAccessRuleId() {
        return documentAccessRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_access_rules.document_access_rule_id
     *
     * @param documentAccessRuleId the value for document_access_rules.document_access_rule_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setDocumentAccessRuleId(String documentAccessRuleId) {
        this.documentAccessRuleId = documentAccessRuleId == null ? null : documentAccessRuleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_access_rules.company_id
     *
     * @return the value of document_access_rules.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_access_rules.company_id
     *
     * @param companyId the value for document_access_rules.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_access_rules.document_id
     *
     * @return the value of document_access_rules.document_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_access_rules.document_id
     *
     * @param documentId the value for document_access_rules.document_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setDocumentId(String documentId) {
        this.documentId = documentId == null ? null : documentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_access_rules.role_id
     *
     * @return the value of document_access_rules.role_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_access_rules.role_id
     *
     * @param roleId the value for document_access_rules.role_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_access_rules.department_id
     *
     * @return the value of document_access_rules.department_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_access_rules.department_id
     *
     * @param departmentId the value for document_access_rules.department_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_access_rules.status
     *
     * @return the value of document_access_rules.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_access_rules.status
     *
     * @param status the value for document_access_rules.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_access_rules.created_at
     *
     * @return the value of document_access_rules.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_access_rules.created_at
     *
     * @param createdAt the value for document_access_rules.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}