package com.sme.be_sme.modules.document.infrastructure.persistence.entity;

import java.util.Date;

public class DocumentCategoryEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_categories.document_category_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String documentCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_categories.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_categories.name
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_categories.description
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_categories.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_categories.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_categories.updated_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_categories.document_category_id
     *
     * @return the value of document_categories.document_category_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getDocumentCategoryId() {
        return documentCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_categories.document_category_id
     *
     * @param documentCategoryId the value for document_categories.document_category_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setDocumentCategoryId(String documentCategoryId) {
        this.documentCategoryId = documentCategoryId == null ? null : documentCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_categories.company_id
     *
     * @return the value of document_categories.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_categories.company_id
     *
     * @param companyId the value for document_categories.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_categories.name
     *
     * @return the value of document_categories.name
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_categories.name
     *
     * @param name the value for document_categories.name
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_categories.description
     *
     * @return the value of document_categories.description
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_categories.description
     *
     * @param description the value for document_categories.description
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_categories.status
     *
     * @return the value of document_categories.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_categories.status
     *
     * @param status the value for document_categories.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_categories.created_at
     *
     * @return the value of document_categories.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_categories.created_at
     *
     * @param createdAt the value for document_categories.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_categories.updated_at
     *
     * @return the value of document_categories.updated_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_categories.updated_at
     *
     * @param updatedAt the value for document_categories.updated_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}