package com.sme.be_sme.modules.onboarding.infrastructure.mapper;

import com.sme.be_sme.modules.onboarding.infrastructure.persistence.entity.ChecklistTemplateEntity;
import java.util.List;

public interface ChecklistTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checklist_templates
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String checklistTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checklist_templates
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(ChecklistTemplateEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checklist_templates
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    ChecklistTemplateEntity selectByPrimaryKey(String checklistTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checklist_templates
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<ChecklistTemplateEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checklist_templates
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(ChecklistTemplateEntity row);
}