package com.sme.be_sme.modules.onboarding.infrastructure.mapper;

import com.sme.be_sme.modules.onboarding.infrastructure.persistence.entity.OnboardingInstanceEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface OnboardingInstanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onboarding_instances
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String onboardingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onboarding_instances
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(OnboardingInstanceEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onboarding_instances
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    OnboardingInstanceEntity selectByPrimaryKey(String onboardingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onboarding_instances
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<OnboardingInstanceEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onboarding_instances
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(OnboardingInstanceEntity row);

    OnboardingInstanceEntity selectByCompanyIdAndRequestNo(
            @Param("companyId") String companyId,
            @Param("requestNo") String requestNo
    );
}