package com.sme.be_sme.modules.onboarding.infrastructure.mapper;

import com.sme.be_sme.modules.onboarding.infrastructure.persistence.entity.OnboardingTemplateEntity;
import java.util.List;

public interface OnboardingTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onboarding_templates
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int deleteByPrimaryKey(String onboardingTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onboarding_templates
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int insert(OnboardingTemplateEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onboarding_templates
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    OnboardingTemplateEntity selectByPrimaryKey(String onboardingTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onboarding_templates
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    List<OnboardingTemplateEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onboarding_templates
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int updateByPrimaryKey(OnboardingTemplateEntity row);
}