package com.sme.be_sme.modules.onboarding.infrastructure.mapper;

import com.sme.be_sme.modules.onboarding.infrastructure.persistence.entity.OnboardingEventEntity;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface OnboardingEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onboarding_events
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String onboardingEventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onboarding_events
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(OnboardingEventEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onboarding_events
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    OnboardingEventEntity selectByPrimaryKey(String onboardingEventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onboarding_events
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<OnboardingEventEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onboarding_events
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(OnboardingEventEntity row);
}