package com.sme.be_sme.modules.onboarding.infrastructure.mapper;

import com.sme.be_sme.modules.onboarding.infrastructure.persistence.entity.TaskAttachmentEntity;
import java.util.List;

public interface TaskAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attachments
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String taskAttachmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attachments
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(TaskAttachmentEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attachments
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    TaskAttachmentEntity selectByPrimaryKey(String taskAttachmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attachments
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<TaskAttachmentEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attachments
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(TaskAttachmentEntity row);
}