package com.sme.be_sme.modules.onboarding.infrastructure.mapper;

import com.sme.be_sme.modules.onboarding.infrastructure.persistence.entity.TaskActivityLogEntity;
import java.util.List;

public interface TaskActivityLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_activity_logs
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String taskActivityLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_activity_logs
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(TaskActivityLogEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_activity_logs
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    TaskActivityLogEntity selectByPrimaryKey(String taskActivityLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_activity_logs
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<TaskActivityLogEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_activity_logs
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(TaskActivityLogEntity row);
}