package com.sme.be_sme.modules.onboarding.infrastructure.mapper;

import com.sme.be_sme.modules.onboarding.infrastructure.persistence.entity.TaskInstanceEntity;
import java.util.List;

public interface TaskInstanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_instances
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_instances
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(TaskInstanceEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_instances
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    TaskInstanceEntity selectByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_instances
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<TaskInstanceEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_instances
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(TaskInstanceEntity row);
}