package com.sme.be_sme.modules.onboarding.infrastructure.mapper;

import com.sme.be_sme.modules.onboarding.infrastructure.persistence.entity.TaskTemplateEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

@Mapper
public interface TaskTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_templates
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String taskTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_templates
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(TaskTemplateEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_templates
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    TaskTemplateEntity selectByPrimaryKey(String taskTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_templates
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<TaskTemplateEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_templates
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(TaskTemplateEntity row);

    int updateStatusByOnboardingTemplateId(
            @Param("onboardingTemplateId") String onboardingTemplateId,
            @Param("status") String status,
            @Param("updatedAt") Date updatedAt
    );
}