package com.sme.be_sme.modules.employee.infrastructure.mapper;

import com.sme.be_sme.modules.employee.infrastructure.persistence.entity.EmployeeProfileEntity;
import java.util.List;

public interface EmployeeProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_profiles
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int deleteByPrimaryKey(String employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_profiles
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int insert(EmployeeProfileEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_profiles
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    EmployeeProfileEntity selectByPrimaryKey(String employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_profiles
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    List<EmployeeProfileEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_profiles
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int updateByPrimaryKey(EmployeeProfileEntity row);
}