package com.sme.be_sme.modules.identity.infrastructure.mapper;

import com.sme.be_sme.modules.identity.infrastructure.persistence.entity.RolePermissionEntity;
import java.util.List;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int deleteByPrimaryKey(String rolePermissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int insert(RolePermissionEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    RolePermissionEntity selectByPrimaryKey(String rolePermissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    List<RolePermissionEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permissions
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int updateByPrimaryKey(RolePermissionEntity row);
}