package com.sme.be_sme.modules.survey.infrastructure.persistence.entity;

import java.util.Date;
public class SurveyQuestionEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_questions.survey_question_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String surveyQuestionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_questions.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_questions.survey_template_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String surveyTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_questions.type
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_questions.content
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_questions.required
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Boolean required;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_questions.sort_order
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_questions.options_json
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Object optionsJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_questions.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_questions.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date updatedAt;

    private String dimensionCode;    // JOB_CLARITY, MANAGER_SUPPORT...
    private Boolean measurable;      // use for counting API or not
    private Integer scaleMin;        // min = 1
    private Integer scaleMax;       // min = 5


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_questions.survey_question_id
     *
     * @return the value of survey_questions.survey_question_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getSurveyQuestionId() {
        return surveyQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_questions.survey_question_id
     *
     * @param surveyQuestionId the value for survey_questions.survey_question_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setSurveyQuestionId(String surveyQuestionId) {
        this.surveyQuestionId = surveyQuestionId == null ? null : surveyQuestionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_questions.company_id
     *
     * @return the value of survey_questions.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_questions.company_id
     *
     * @param companyId the value for survey_questions.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_questions.survey_template_id
     *
     * @return the value of survey_questions.survey_template_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getSurveyTemplateId() {
        return surveyTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_questions.survey_template_id
     *
     * @param surveyTemplateId the value for survey_questions.survey_template_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setSurveyTemplateId(String surveyTemplateId) {
        this.surveyTemplateId = surveyTemplateId == null ? null : surveyTemplateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_questions.type
     *
     * @return the value of survey_questions.type
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_questions.type
     *
     * @param type the value for survey_questions.type
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_questions.content
     *
     * @return the value of survey_questions.content
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_questions.content
     *
     * @param content the value for survey_questions.content
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_questions.required
     *
     * @return the value of survey_questions.required
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Boolean getRequired() {
        return required;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_questions.required
     *
     * @param required the value for survey_questions.required
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setRequired(Boolean required) {
        this.required = required;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_questions.sort_order
     *
     * @return the value of survey_questions.sort_order
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_questions.sort_order
     *
     * @param sortOrder the value for survey_questions.sort_order
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_questions.options_json
     *
     * @return the value of survey_questions.options_json
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Object getOptionsJson() {
        return optionsJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_questions.options_json
     *
     * @param optionsJson the value for survey_questions.options_json
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setOptionsJson(Object optionsJson) {
        this.optionsJson = optionsJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_questions.created_at
     *
     * @return the value of survey_questions.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_questions.created_at
     *
     * @param createdAt the value for survey_questions.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_questions.updated_at
     *
     * @return the value of survey_questions.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_questions.updated_at
     *
     * @param updatedAt the value for survey_questions.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }


    public String getDimensionCode() {
        return dimensionCode;
    }

    public void setDimensionCode(String dimensionCode) {
        this.dimensionCode = dimensionCode;
    }

    public Boolean getMeasurable() {
        return measurable;
    }

    public void setMeasurable(Boolean measurable) {
        this.measurable = measurable;
    }

    public Integer getScaleMin() {
        return scaleMin;
    }

    public void setScaleMin(Integer scaleMin) {
        this.scaleMin = scaleMin;
    }

    public Integer getScaleMax() {
        return scaleMax;
    }

    public void setScaleMax(Integer scaleMax) {
        this.scaleMax = scaleMax;
    }
}