package com.sme.be_sme.modules.survey.infrastructure.persistence.entity;

import java.util.Date;

public class SurveyInstanceEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_instances.survey_instance_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String surveyInstanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_instances.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_instances.onboarding_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String onboardingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_instances.survey_template_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String surveyTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_instances.scheduled_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date scheduledAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_instances.sent_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date sentAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_instances.closed_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date closedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_instances.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_instances.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_instances.survey_instance_id
     *
     * @return the value of survey_instances.survey_instance_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getSurveyInstanceId() {
        return surveyInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_instances.survey_instance_id
     *
     * @param surveyInstanceId the value for survey_instances.survey_instance_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setSurveyInstanceId(String surveyInstanceId) {
        this.surveyInstanceId = surveyInstanceId == null ? null : surveyInstanceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_instances.company_id
     *
     * @return the value of survey_instances.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_instances.company_id
     *
     * @param companyId the value for survey_instances.company_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_instances.onboarding_id
     *
     * @return the value of survey_instances.onboarding_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getOnboardingId() {
        return onboardingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_instances.onboarding_id
     *
     * @param onboardingId the value for survey_instances.onboarding_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setOnboardingId(String onboardingId) {
        this.onboardingId = onboardingId == null ? null : onboardingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_instances.survey_template_id
     *
     * @return the value of survey_instances.survey_template_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getSurveyTemplateId() {
        return surveyTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_instances.survey_template_id
     *
     * @param surveyTemplateId the value for survey_instances.survey_template_id
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setSurveyTemplateId(String surveyTemplateId) {
        this.surveyTemplateId = surveyTemplateId == null ? null : surveyTemplateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_instances.scheduled_at
     *
     * @return the value of survey_instances.scheduled_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getScheduledAt() {
        return scheduledAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_instances.scheduled_at
     *
     * @param scheduledAt the value for survey_instances.scheduled_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setScheduledAt(Date scheduledAt) {
        this.scheduledAt = scheduledAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_instances.sent_at
     *
     * @return the value of survey_instances.sent_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getSentAt() {
        return sentAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_instances.sent_at
     *
     * @param sentAt the value for survey_instances.sent_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setSentAt(Date sentAt) {
        this.sentAt = sentAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_instances.closed_at
     *
     * @return the value of survey_instances.closed_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getClosedAt() {
        return closedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_instances.closed_at
     *
     * @param closedAt the value for survey_instances.closed_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setClosedAt(Date closedAt) {
        this.closedAt = closedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_instances.status
     *
     * @return the value of survey_instances.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_instances.status
     *
     * @param status the value for survey_instances.status
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_instances.created_at
     *
     * @return the value of survey_instances.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_instances.created_at
     *
     * @param createdAt the value for survey_instances.created_at
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}