package com.sme.be_sme.modules.survey.infrastructure.persistence.entity;

import java.math.BigDecimal;
import java.util.Date;

public class SurveyResponseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_responses.survey_response_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String surveyResponseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_responses.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_responses.survey_instance_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String surveyInstanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_responses.responder_user_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String responderUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_responses.overall_score
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private BigDecimal overallScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_responses.submitted_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date submittedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_responses.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_responses.survey_response_id
     *
     * @return the value of survey_responses.survey_response_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getSurveyResponseId() {
        return surveyResponseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_responses.survey_response_id
     *
     * @param surveyResponseId the value for survey_responses.survey_response_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setSurveyResponseId(String surveyResponseId) {
        this.surveyResponseId = surveyResponseId == null ? null : surveyResponseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_responses.company_id
     *
     * @return the value of survey_responses.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_responses.company_id
     *
     * @param companyId the value for survey_responses.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_responses.survey_instance_id
     *
     * @return the value of survey_responses.survey_instance_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getSurveyInstanceId() {
        return surveyInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_responses.survey_instance_id
     *
     * @param surveyInstanceId the value for survey_responses.survey_instance_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setSurveyInstanceId(String surveyInstanceId) {
        this.surveyInstanceId = surveyInstanceId == null ? null : surveyInstanceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_responses.responder_user_id
     *
     * @return the value of survey_responses.responder_user_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getResponderUserId() {
        return responderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_responses.responder_user_id
     *
     * @param responderUserId the value for survey_responses.responder_user_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setResponderUserId(String responderUserId) {
        this.responderUserId = responderUserId == null ? null : responderUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_responses.overall_score
     *
     * @return the value of survey_responses.overall_score
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public BigDecimal getOverallScore() {
        return overallScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_responses.overall_score
     *
     * @param overallScore the value for survey_responses.overall_score
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setOverallScore(BigDecimal overallScore) {
        this.overallScore = overallScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_responses.submitted_at
     *
     * @return the value of survey_responses.submitted_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getSubmittedAt() {
        return submittedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_responses.submitted_at
     *
     * @param submittedAt the value for survey_responses.submitted_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setSubmittedAt(Date submittedAt) {
        this.submittedAt = submittedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_responses.created_at
     *
     * @return the value of survey_responses.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_responses.created_at
     *
     * @param createdAt the value for survey_responses.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}