package com.sme.be_sme.modules.survey.infrastructure.persistence.entity;

import java.util.Date;

public class SurveyTemplateEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_templates.survey_template_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String surveyTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_templates.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_templates.name
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_templates.stage
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String stage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_templates.manager_only
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Boolean managerOnly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_templates.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_templates.created_by
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_templates.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_templates.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_templates.survey_template_id
     *
     * @return the value of survey_templates.survey_template_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getSurveyTemplateId() {
        return surveyTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_templates.survey_template_id
     *
     * @param surveyTemplateId the value for survey_templates.survey_template_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setSurveyTemplateId(String surveyTemplateId) {
        this.surveyTemplateId = surveyTemplateId == null ? null : surveyTemplateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_templates.company_id
     *
     * @return the value of survey_templates.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_templates.company_id
     *
     * @param companyId the value for survey_templates.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_templates.name
     *
     * @return the value of survey_templates.name
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_templates.name
     *
     * @param name the value for survey_templates.name
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_templates.stage
     *
     * @return the value of survey_templates.stage
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getStage() {
        return stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_templates.stage
     *
     * @param stage the value for survey_templates.stage
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setStage(String stage) {
        this.stage = stage == null ? null : stage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_templates.manager_only
     *
     * @return the value of survey_templates.manager_only
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Boolean getManagerOnly() {
        return managerOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_templates.manager_only
     *
     * @param managerOnly the value for survey_templates.manager_only
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setManagerOnly(Boolean managerOnly) {
        this.managerOnly = managerOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_templates.status
     *
     * @return the value of survey_templates.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_templates.status
     *
     * @param status the value for survey_templates.status
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_templates.created_by
     *
     * @return the value of survey_templates.created_by
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_templates.created_by
     *
     * @param createdBy the value for survey_templates.created_by
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_templates.created_at
     *
     * @return the value of survey_templates.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_templates.created_at
     *
     * @param createdAt the value for survey_templates.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_templates.updated_at
     *
     * @return the value of survey_templates.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_templates.updated_at
     *
     * @param updatedAt the value for survey_templates.updated_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}