package com.sme.be_sme.modules.survey.infrastructure.persistence.entity;

import java.util.Date;

public class SurveyAnswerEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_answers.survey_answer_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String surveyAnswerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_answers.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_answers.survey_response_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String surveyResponseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_answers.survey_question_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String surveyQuestionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_answers.value_text
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String valueText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_answers.value_rating
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Integer valueRating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_answers.value_choice
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private String valueChoice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column survey_answers.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    private Date createdAt;

    private Object valueChoices;
    private String questionType;
    private String dimensionCode;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_answers.survey_answer_id
     *
     * @return the value of survey_answers.survey_answer_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getSurveyAnswerId() {
        return surveyAnswerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_answers.survey_answer_id
     *
     * @param surveyAnswerId the value for survey_answers.survey_answer_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setSurveyAnswerId(String surveyAnswerId) {
        this.surveyAnswerId = surveyAnswerId == null ? null : surveyAnswerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_answers.company_id
     *
     * @return the value of survey_answers.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_answers.company_id
     *
     * @param companyId the value for survey_answers.company_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_answers.survey_response_id
     *
     * @return the value of survey_answers.survey_response_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getSurveyResponseId() {
        return surveyResponseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_answers.survey_response_id
     *
     * @param surveyResponseId the value for survey_answers.survey_response_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setSurveyResponseId(String surveyResponseId) {
        this.surveyResponseId = surveyResponseId == null ? null : surveyResponseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_answers.survey_question_id
     *
     * @return the value of survey_answers.survey_question_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getSurveyQuestionId() {
        return surveyQuestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_answers.survey_question_id
     *
     * @param surveyQuestionId the value for survey_answers.survey_question_id
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setSurveyQuestionId(String surveyQuestionId) {
        this.surveyQuestionId = surveyQuestionId == null ? null : surveyQuestionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_answers.value_text
     *
     * @return the value of survey_answers.value_text
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getValueText() {
        return valueText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_answers.value_text
     *
     * @param valueText the value for survey_answers.value_text
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setValueText(String valueText) {
        this.valueText = valueText == null ? null : valueText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_answers.value_rating
     *
     * @return the value of survey_answers.value_rating
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Integer getValueRating() {
        return valueRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_answers.value_rating
     *
     * @param valueRating the value for survey_answers.value_rating
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setValueRating(Integer valueRating) {
        this.valueRating = valueRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_answers.value_choice
     *
     * @return the value of survey_answers.value_choice
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public String getValueChoice() {
        return valueChoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_answers.value_choice
     *
     * @param valueChoice the value for survey_answers.value_choice
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setValueChoice(String valueChoice) {
        this.valueChoice = valueChoice == null ? null : valueChoice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column survey_answers.created_at
     *
     * @return the value of survey_answers.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column survey_answers.created_at
     *
     * @param createdAt the value for survey_answers.created_at
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Object getValueChoices() {
        return valueChoices;
    }

    public void setValueChoices(Object valueChoices) {
        this.valueChoices = valueChoices;
    }

    public String getQuestionType() {
        return questionType;
    }

    public void setQuestionType(String questionType) {
        this.questionType = questionType;
    }

    public String getDimensionCode() {
        return dimensionCode;
    }

    public void setDimensionCode(String dimensionCode) {
        this.dimensionCode = dimensionCode;
    }

}