package com.sme.be_sme.modules.billing.infrastructure.mapper;

import com.sme.be_sme.modules.billing.infrastructure.persistence.entity.DiscountCodeEntity;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface DiscountCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discount_codes
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String discountCodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discount_codes
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(DiscountCodeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discount_codes
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    DiscountCodeEntity selectByPrimaryKey(String discountCodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discount_codes
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<DiscountCodeEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discount_codes
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(DiscountCodeEntity row);
}