package com.sme.be_sme.modules.billing.infrastructure.mapper;

import com.sme.be_sme.modules.billing.infrastructure.persistence.entity.DunningCaseEntity;
import java.util.List;

public interface DunningCaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dunning_cases
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String dunningCaseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dunning_cases
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(DunningCaseEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dunning_cases
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    DunningCaseEntity selectByPrimaryKey(String dunningCaseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dunning_cases
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<DunningCaseEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dunning_cases
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(DunningCaseEntity row);
}