package com.sme.be_sme.modules.billing.infrastructure.mapper;

import com.sme.be_sme.modules.billing.infrastructure.persistence.entity.InvoiceEntity;
import java.util.List;

public interface InvoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String invoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(InvoiceEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    InvoiceEntity selectByPrimaryKey(String invoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<InvoiceEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invoices
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(InvoiceEntity row);
}