package com.sme.be_sme.modules.billing.infrastructure.mapper;

import com.sme.be_sme.modules.billing.infrastructure.persistence.entity.PaymentTransactionEntity;
import java.util.List;

public interface PaymentTransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_transactions
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int deleteByPrimaryKey(String paymentTransactionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_transactions
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int insert(PaymentTransactionEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_transactions
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    PaymentTransactionEntity selectByPrimaryKey(String paymentTransactionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_transactions
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    List<PaymentTransactionEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_transactions
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int updateByPrimaryKey(PaymentTransactionEntity row);
}