package com.sme.be_sme.modules.billing.infrastructure.mapper;

import com.sme.be_sme.modules.billing.infrastructure.persistence.entity.PlanEntity;
import java.util.List;

public interface PlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plans
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int deleteByPrimaryKey(String planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plans
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int insert(PlanEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plans
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    PlanEntity selectByPrimaryKey(String planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plans
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    List<PlanEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plans
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int updateByPrimaryKey(PlanEntity row);
}