package com.sme.be_sme.modules.billing.infrastructure.mapper;

import com.sme.be_sme.modules.billing.infrastructure.persistence.entity.SubscriptionEntity;
import java.util.List;

public interface SubscriptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String subscriptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(SubscriptionEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    SubscriptionEntity selectByPrimaryKey(String subscriptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<SubscriptionEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriptions
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(SubscriptionEntity row);
}