package com.sme.be_sme.modules.billing.infrastructure.mapper;

import com.sme.be_sme.modules.billing.infrastructure.persistence.entity.SubscriptionDiscountEntity;
import java.util.List;

public interface SubscriptionDiscountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscription_discounts
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int deleteByPrimaryKey(String subscriptionDiscountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscription_discounts
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int insert(SubscriptionDiscountEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscription_discounts
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    SubscriptionDiscountEntity selectByPrimaryKey(String subscriptionDiscountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscription_discounts
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    List<SubscriptionDiscountEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscription_discounts
     *
     * @mbg.generated Thu Jan 22 10:05:03 ICT 2026
     */
    int updateByPrimaryKey(SubscriptionDiscountEntity row);
}