package com.sme.be_sme.modules.billing.infrastructure.mapper;

import com.sme.be_sme.modules.billing.infrastructure.persistence.entity.UsageMonthlyEntity;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface UsageMonthlyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usage_monthly
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int deleteByPrimaryKey(String usageMonthlyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usage_monthly
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int insert(UsageMonthlyEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usage_monthly
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    UsageMonthlyEntity selectByPrimaryKey(String usageMonthlyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usage_monthly
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    List<UsageMonthlyEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usage_monthly
     *
     * @mbg.generated Thu Jan 22 16:08:37 ICT 2026
     */
    int updateByPrimaryKey(UsageMonthlyEntity row);
}